Backend/Backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls'))
]

Backend/api/urls.py
from django.urls import path
from . import views
from .views import RegUpdateView, RegDelView, DocUpdateView
from django.conf import settings
from django.conf.urls.static import static
from django.forms.widgets import Media
from django.contrib.auth import views as auth_views
app_name = 'api'

urlpatterns = [
    # path('', views.getRoutes, name='routes'),
    path('', views.index, name='index'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('Notes/', views.getNotes, name='notes'),
    path('NewProject/', views.newProject, name='newproject'),
    # path('ProjectList/', views.projectList, name='projectlist'),
    path('NewReg/', views.newRegistration, name='newReg'),
    path('Reg/edit/<int:pk>', views.RegUpdateView.as_view(), name="regupdate"),
    path('<int:pk>/delete/', views.RegDelView.as_view(), name='regdelete'),
    # path('RegLists/', views.newRegistrationList, name='reglists'),
    # path('RegList/<str:pk>', views.registrationList, name='reglist'),
    path('NewDoc/', views.newDocuments, name='newdoc'),
    path('Doc/edit/<int:pk>', views.DocUpdateView.as_view(), name='docupdate'),
    path('user_details/', views.user_details, name='user_details'),
    # path('DocLists/', views.documentsList, name='docslist'),
    # path('DocList/<str:pk>', views.documentList, name='doclist')    
    path('sites/', views.sites, name='sites'),
    path('details/<int:pk>', views.plot_details, name='details'),
    path('ajax/load-plot_nos/', views.load_plot_no, name='ajax_load_plot_no'),
    path('ajax/load-plot-no/', views.load_plot_nos, name='ajax_load_plot_nos'),
    #path('plotAmount/', views.plotAmout, name='plotamount'),
    #path('amount_details/', views.amountDetails, name='Adetails'),
    path('plotAvailablilty/', views.plotAvailability, name='plotavailability')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/api/models.py
from django.db import models

# Create your models here.

    

# add new projects here
    
class New_Project(models.Model):
    project_name = models.CharField(max_length=100, unique=True, blank=False, null=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.project_name

class Note(models.Model):
   
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.body[0:50]

# here we are creating first step of registration form 

class New_registration(models.Model):
    
    STATE = (
        ('AP', 'Andhra Pradesh'),
        ('TS', 'Telangana')
    )
    
    project_name = models.ForeignKey(New_Project, on_delete=models.CASCADE)
    plot_no = models.CharField(max_length=20, unique=False, blank=False, null=False)
    first_name = models.CharField(max_length=100, blank=False, null=False)
    last_name = models.CharField(max_length=100, blank=False, null=False)
    mail_id = models.EmailField(max_length=100, blank=False, null=False)
    mobile_number = models.BigIntegerField(("mobile number"), unique=True, blank=False, null=False)
    survey_no = models.CharField(max_length=50, blank=False, null=False)
    land_extent = models.CharField(max_length=150, blank=False, null=False)
    address = models.CharField(max_length=75, blank=True, null=True)
    community = models.CharField(max_length=75, blank=False, null=False)
    city = models.CharField(max_length=50, blank=False, null=False)
    district = models.CharField(max_length=50, blank=False, null=False)
    state = models.CharField(max_length=50, choices=STATE)
    pincode = models.PositiveSmallIntegerField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.plot_no
    
# here we are creating second step registration form details
    
class Document_details(models.Model):
    project_name = models.ForeignKey(New_Project, on_delete=models.CASCADE)
    plot_no = models.ForeignKey(New_registration, on_delete=models.CASCADE, related_name='plot_nos')
    katha_no = models.CharField(max_length=50)
    passbook_no = models.CharField(max_length=50)
    document_no = models.CharField(max_length=100, unique=True)
    aadhar_no = models.BigIntegerField(unique=True)
    # total_amount = models.PositiveIntegerField()
    # paid_amount = models.PositiveIntegerField(default=0)
    pass_photo = models.ImageField(upload_to='api/images/pass_photos')
    passbook_photo = models.ImageField(upload_to='api/images/passbook_photos')
    note = models.TextField(null=True,help_text='enter text here')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.project_name.project_name
    
class post_image(models.Model):
    post = models.ForeignKey(Document_details, default=None, on_delete=models.CASCADE)
    documents_images = models.ImageField(upload_to='api/images/document_images')
    document_files = models.FileField(upload_to='api/files', null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.post.plot_no)
    
class PostImage(models.Model):
    post = models.ForeignKey(Document_details, default=None, on_delete=models.CASCADE)
    document_photos = models.FileField(upload_to = 'api/images/documents')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return str(self.post.plot_no)
    
class PlotAvailability(models.Model):
    project_name = models.ForeignKey(New_Project, on_delete=models.CASCADE)
    plot_no = models.CharField(max_length=20, unique=False, blank=False, null=False)
    land_extent = models.CharField(max_length=150, blank=False, null=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.plot_no)
    
class PlotAmount(models.Model):
    project_name = models.ForeignKey(New_Project, on_delete=models.CASCADE)
    plot_no = models.ForeignKey(Document_details, on_delete=models.CASCADE, related_name='plot_nos')
    add_amount = models.PositiveIntegerField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.plot_no.plot_no)

Backend/api/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
#from django.http import JsonResponse
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.parsers import JSONParser
from django.contrib.auth.decorators import login_required
from .models import Note, New_registration, Document_details, post_image, New_Project, PostImage, PlotAmount, PlotAvailability
from .serializers import NoteSerializer, NewRegistrationSerializer, NewDocumentSerializer, NewProjectSerializer
# Create your views here.
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.conf import settings
from api import forms
from .forms import NoteForm, NewProjectForm, NewRegistrationForm, NewDocumentForm, DocumentImageForm, PlotAmountForm
from django.db.models import Q
from django.utils.decorators import method_decorator

@login_required
def index(request):
    return render(request, "index.html")

# def getNotes(request):
#     Notes = Note.objects.all()
#     return render(request, 'notes.html', {'data':Notes})

#creating new projects
@login_required
def newProject(request):
    if request.method == 'POST':
        form = NewProjectForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you! Plot Account Was Successfully Created.',
                             extra_tags='alert alert-success')
            form = NewProjectForm() 
        else:
            print(form.errors)
            messages.warning(request, 'Sorry, Something went wrong!', extra_tags='alert alert-warning')
    else:
        form = NewProjectForm() 
    return render(request, 'newproject.html', {'form': form})

# creating the new registration form 
@login_required
def newRegistration(request):
    if request.method == 'POST':
        form = NewRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you! Plot Account Was Successfully Created.',
                             extra_tags='alert alert-success')
            form= NewRegistrationForm()
        else:
            print(form.errors)
            messages.warning(request, 'Sorry, Something went wrong!', extra_tags='alert alert-warning')                     
    else:
        form= NewRegistrationForm()
    return render(request, 'newregistration.html', {'form': form})
#

class RegUpdateView(LoginRequiredMixin,UpdateView):
    model = New_registration
    fields = "__all__"
    template_name = 'reg_update_view.html'
    success_url = '/'
    
class RegDelView(LoginRequiredMixin, DeleteView):
    model = New_registration
    success_url ="/"
    template_name = "reg_delete_view.html"

#user details list
@login_required
def user_details(request):
    plot = PlotAvailability.objects.all()
    pro = New_Project.objects.all()
    query = Document_details.objects.all()
    return render(request, 'user_details.html', {"query": query, 'pro': pro, 'plot': plot})
    
# # getting all registration details
# @login_required
# def newRegistrationList(request):
#     registrations = New_registration.objects.all()
#     return render(request, "registration_list.html", {'data': registrations})
    
#  # getting the list of single registraion details   
# def registrationList(request, pk):
#     registration = New_registration.objects.get(id=pk)
#     return render(request, "registration_pk.html", {'data': registration})

    
# creating the new document form
@login_required
def newDocuments(request):
    if request.method =='POST':
        form = DocumentImageForm(request.POST or None, request.FILES)
        images = request.FILES.getlist('document_photos')
        if form.is_valid():
            # project_name = form.cleaned_data.get('project_name')
            # plot_no = form.cleaned_data.get('plot_no')
            # katha_no = form.cleaned_data.get('katha_no')
            # new_passbook_no = form.cleaned_data.get('new_passbook_no')
            # document_no = form.cleaned_data.get('document_no')
            # aadhar_no = form.cleaned_data.get('aadhar_no')
            # pass_photo = form.cleaned_data.get('pass_photo')
            # passbook_photo = form.cleaned_data.get('passbook_photo')
            # Note = form.cleaned_data.get('Note')
            # object = Document_details(
            #     project_name=project_name,
            #     plot_no=plot_no,
            #     katha_no=katha_no,
            #     new_passbook_no=new_passbook_no,                  
            #     document_no=document_no,
            #     aadhar_no=aadhar_no,
            #     pass_photo=pass_photo,
            #     passbook_photo=passbook_photo,
            #     Note=Note,
            # )
            obj = form.save()
            for i in images:
                data = PostImage(post=obj, document_photos=i)
                data.save()
            form = DocumentImageForm()
            """    
            variable = Extent_sites(post=object, project=object.project_name,variable_plot=object.plot_no, checked = True)
            variable.save()
            """
            messages.success(request, 'Thank you! Plot Account Was Successfully Created.',
                             extra_tags='alert alert-success')           
        else:
            print(form.errors)
            messages.warning(request, 'Sorry, Something went wrong!', extra_tags='alert alert-warning')                     
            
    else:
        form = DocumentImageForm()
    return render(request, 'newdocuments.html', {'form': form})

class DocUpdateView(UpdateView):
    model = Document_details
    form_class = NewDocumentForm
    template_name = 'doc_update_view.html'
    success_url = '/'

def load_plot_no(request):
    project_name_id = request.GET.get('projectId')
    plot_nos = New_registration.objects.raw('select * from api_new_registration where api_new_registration.project_name_id = %s', [project_name_id])
    return render(request, 'dropdown_list_options.html',  {'plot_nos': plot_nos})
 
@login_required   
def sites(request):
    QuerySet = ''
    query = request.GET.get('q', None)
    if query:
        first_name = query.split(' ')[0]
        last_name  = query.split(' ')[0]
        QuerySet = Document_details.objects.filter(Q(plot_no__plot_no__icontains=query) | Q(plot_no__mobile_number__icontains=query) 
                    | Q(plot_no__mail_id__icontains=query) | Q(project_name__project_name__icontains=query)
                    | Q(plot_no__first_name__icontains=first_name) | Q(plot_no__last_name__icontains=last_name)
                    | Q(plot_no__first_name__icontains=last_name) | Q(plot_no__last_name__icontains=first_name))
    return render(request, 'sites.html', {'QuerySet': QuerySet})

@login_required
def plot_details(request, pk):
    #query = New_registration.objects.filter(pk=pk)
    query = Document_details.objects.filter(pk=pk)
    query1 = PostImage.objects.filter(post__in=query)
    
    return render(request, 'details.html', {'query': query, 'query1':query1, 'media_url':settings.MEDIA_URL})

# 

def load_plot_nos(request):
    project_name_id = request.GET.get('projectId')
    plot_nos = Document_details.objects.raw('select * from api_document_details where api_document_details.project_name_id = %s', [project_name_id])
    return render(request, 'dropdown_list_options1.html',  {'plot_nos': plot_nos})


@login_required
def plotAvailability(request):
    return render(request, 'plot_availability.html')

# @api_view(['GET'])
# def getRoutes(request):
#     routes = []    
#     return Response(routes)

#@api_view(['GET'])
# def getNotes(request):
#     Notes = Note.objects.all()
#     serializer = NoteSerializer(Notes, many=True)
#     return Response(serializer.data)

# @api_view(['POST'])
# def newProject(request):
#     if request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = NewProjectSerializer(data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=201)
#         return Response(serializer.errors, status=400)

# getting projects list
# @api_view(['GET'])
# def projectList(request):
#     projects = New_Project.objects.all()
#     serializer = NewProjectSerializer(projects, many=True)
#     return Response(serializer.data)


#@csrf_exempt
# @api_view(['POST'])
# def newRegistration(request):
#     if request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = NewRegistrationSerializer(data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data, status=201)
#         return Response(serializer.errors, status=400) 

# @api_view(['GET'])
# def newRegistrationList(request):
#     registrations = New_registration.objects.all()
#     serializer = NewRegistrationSerializer(registrations, many=True)
#     return Response(serializer.data)

# @api_view(['POST'])
# def newDocuments(request):
#     if request.method == "POST":
#         data = JSONParser().parse(request, request.FILES)
#         serializer = NewDocumentSerializer(data=data)
#         files = request.FILES.getlist('document_files')
#         images = request.IMAGES.getlist('documents_images')
#         if serializer.is_valid():
#             serializer.save()
#             for f, i in files, images:
#                 data = post_image(post=serializer, documents_images=i, document_files=f)
#                 data.save()
#             return Response(serializer.data, status=200)
#         return Response(serializer.errors, status=400)
    
    
# @api_view(['GET'])
# def registrationList(request, pk):
#     registration = New_registration.objects.get(id=pk)
#     serializer = NewRegistrationSerializer(registration, many=False)

Backend/api/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Inacres</title>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/@popperjs/core@2/dist/umd/popper.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </head>
  <body>
    {% if user.is_authenticated %}
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <b><a class="navbar-brand" href="#">Inacres Database</a></b>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <b><span class="navbar-toggler-icon"></span></b>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Inacres</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <b><a class="nav-link active" aria-current="page" href="{% url 'api:index' %}">Home</a></b>
              </li>
              <li class="nav-item">
                <b><a class="nav-link" href="{% url 'api:newReg' %}">Step-1: User Registration</a></b>
              </li>
              {% if user.is_authenticated and user.is_staff %}
              <li class="nav-item">
                <b><a class="nav-link" href="{% url 'api:newdoc' %}">Step-2: User Document Regstration</a></b>
              </li>
              {% endif %}
              <li class="nav-item">
                <b><a class="nav-link" href="{% url 'api:user_details' %}">Plots Available</a></b>
              </li>
              <li class="nav-item">
                <b><a class="nav-link" href="{% url 'api:sites' %}">Sites</a></b>
              </li>
              {% if user.is_authenticated and user.is_staff and user.is_superuser %}
              <li class="nav-item">
                <b><a class="nav-link" href="{% url 'api:newproject' %}">New Project</a></b>
              </li>
              {% endif %}
              {% comment %} <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Project details
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'api:user_details' %}">Plots Available</a></li>
                  <li><a class="dropdown-item" href="{% url 'api:plotamount' %}">Add Amount</a></li>  
                  <li><a class="dropdown-item" href="{% url 'api:Adetails' %}">Amount Details</a></li>      
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="{% url 'api:sites' %}">Sites</a></li>
                </ul>
              </li> {% endcomment %}
              <li class="nav-item">
                <b><a class="nav-link" href="{% url 'api:logout' %}">Logout</a></b>
              </li>
            </ul>
            <form class="d-flex mt-3" role="search"  method='GET' action='{% url 'api:sites' %}'>
              <input class="form-control me-2" name='q' type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-dark" type="submit">Search</button>
            </form>
          </div>
        </div>
      </div>
    </nav>
  </br>

    {% endif %}
      </br>
      <div class='container'>
        {% block content %}

        {% endblock %}  
    </div> 
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

Backend/api/templates/doc_update_view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} New Registration {% endblock %}
{% block content %}
<section class="h-100" style="background-color: #9CEEE5 ">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-3 d-none d-md-block">
                <img src=""
                  alt="" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
              </div>
              <div class="col-md-6 col-lg-9 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method='POST'>
                    <div class="d-flex align-items-center mb-3 pb-1">
                      <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                      <span class="h1 fw-bold mb-0">Document Update</span>
                    </div>
                    {% if messages %}
                    <div class= 'row'>
                    {% for message in messages %}
                    <div class='col-md-6 col-md-offset-3'> 
                    <div {% if message.tags %} class='alert alert-{{ message.tags }}' role='alert' {% endif %}> {{ message }} </div></div>
                    {% endfor %}
                    </div>
                    {% endif %}</br>
                    {% csrf_token %}
                    <b>{{ form|crispy }}</b>
  
                    <div class="pt-1 mb-4">
                      <button class="btn btn-dark btn-lg btn-block" type="submit">Submit</button>
                      <a href="{% url 'api:index' %}" type="button" class="btn btn-dark btn-lg btn-block" >Homepage</a>
                    </div
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

Backend/api/templates/dropdown_list_options.html
<option value="">------</option>
{% for plot in plot_nos %}
<option value="{{ plot.pk }}">{{ plot.plot_no }}</option>
{% endfor %}

Backend/api/templates/dropdown_list_options1.html
<option value="">------</option>
{% for plot in plot_nos %}
<option value="{{ plot.pk }}">{{ plot.plot_no.plot_no }}</option>
{% endfor %}

Backend/api/templates/newdocuments.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} Document Details {% endblock %}
{% block content %}
<section class="h-100" style="background-color: #9CEEE5 ">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-3 d-none d-md-block">
                <img src=""
                  alt="" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
              </div>
              <div class="col-md-6 col-lg-9 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method='POST' action="{% url 'api:newdoc' %}" id="DocumentForm" data-plotnos-url="{% url 'api:ajax_load_plot_no' %}" enctype="multipart/form-data"  >
                    <div class="d-flex align-items-center mb-3 pb-1">
                      <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                      <span class="h1 fw-bold mb-0">Document Details</span>
                    </div>
                    {% if messages %}
                    <div class= 'row'>
                    {% for message in messages %}
                    <div class='col-md-6 col-md-offset-3'> 
                    <div {% if message.tags %} class='alert alert-{{ message.tags }}' role='alert' {% endif %}> {{ message }} </div></div>
                    {% endfor %}
                    </div>
                    {% endif %}</br>
                    {% csrf_token %}
                    <b>{{ form|crispy }}</b>
  
                    <div class="pt-1 mb-4">
                      <button class="btn btn-dark btn-lg btn-block" type="submit">Submit</button>
                      <a href= "{% url 'api:index' %}" type="button" class="btn btn-dark btn-lg btn-block" >Homepage</a>
                    </div
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
     $("#id_project_name").change(function () {
       var url = $("#DocumentForm").attr("data-plotnos-url");  // get the url of the `load_cities` view
       var projectId = $(this).val();  // get the selected country ID from the HTML input
 
       $.ajax({                       // initialize an AJAX request
         url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
         data: {
           'projectId': projectId       // add the country id to the GET parameters
         },
         success: function (data) {   // `data` is the return of the `load_cities` view function
           $("#id_plot_no").html(data);  // replace the contents of the city input with the data that came from the server
         }
       });
 
     });
   </script>
{% endblock %}

Backend/api/templates/plotamount.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} New Project {% endblock %}

{% block content %}


<section class="vh-100" style="background-color: #9CEEE5 ">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-3 d-none d-md-block">
                <img src=""
                  alt="" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
              </div>
              <div class="col-md-6 col-lg-9 d-flex align-items-center">
                <div class="card-body p-4 p-lg-5 text-black">
  
                  <form method='POST' action="{% url 'api:plotamount' %}" id="PlotAmountForm" data-plotnos-url="{% url 'api:ajax_load_plot_nos' %}" enctype="multipart/form-data" >
                    <div class="d-flex align-items-center mb-3 pb-1">
                      <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                      <span class="h1 fw-bold mb-0">Add Amount</span>
                    </div>
                    {% if messages %}
                    <div class= 'row'>
                    {% for message in messages %}
                    <div class='col-md-6 col-md-offset-3'> 
                    <div {% if message.tags %} class='alert alert-{{ message.tags }}' role='alert' {% endif %}> {{ message }} </div></div>
                    {% endfor %}
                    </div>
                    {% endif %}</br>
                    
                    {% csrf_token %}
                    <b>{{ form|crispy }}</b>
  
                    <div class="pt-1 mb-4">
                      <button class="btn btn-dark btn-lg btn-block" type="submit">Submit</button>
                      <a href="{% url 'api:index' %}" type="button" class="btn btn-dark btn-lg btn-block" >Homepage</a>
                    </div
                  </form>
                  
                  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                  <script>
                     $("#id_project_name").change(function () {
                       var url = $("#PlotAmountForm").attr("data-plotnos-url");  // get the url of the `load_cities` view
                       var projectId = $(this).val();  // get the selected country ID from the HTML input
                 
                       $.ajax({                       // initialize an AJAX request
                         url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
                         data: {
                           'projectId': projectId       // add the country id to the GET parameters
                         },
                         success: function (data) {   // `data` is the return of the `load_cities` view function
                           $("#id_plot_no").html(data);  // replace the contents of the city input with the data that came from the server
                         }
                       });
                 
                     }); 
                   </script>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



{% endblock %}